---
all:
  vars:
    ansible_winrm_transport: kerberos
    ansible_winrm_scheme: https
    ansible_winrm_server_cert_validation: ignore

  children:
    # ── Dell Host Server ──────────────────────────────────────────────────
    hyperv_hosts:
      hosts:
        az-local-host01:
          ansible_host: 192.168.20.10
          ansible_user: "{{ vault_host_admin_user }}"
          ansible_password: "{{ vault_host_admin_pass }}"
          ansible_connection: winrm
          ansible_winrm_port: 5986
          idrac_ip: 192.168.20.254
          idrac_user: "{{ vault_idrac_user }}"
          idrac_pass: "{{ vault_idrac_pass }}"

    # ── Clinical VM ───────────────────────────────────────────────────────
    clinical_vms:
      hosts:
        clinical-vm-01:
          ansible_host: 192.168.10.10
          ansible_user: "{{ vault_vm_admin_user }}"
          ansible_password: "{{ vault_vm_admin_pass }}"
          ansible_connection: winrm
          ansible_winrm_port: 5986
          vm_vlan: 10
          vm_static_ip: 192.168.10.10
          vm_gateway:   192.168.10.1
          vm_dns:       192.168.20.5

    # ── Cisco ASA ─────────────────────────────────────────────────────────
    cisco_asa:
      hosts:
        asa-clinical-poc:
          ansible_host:       192.168.20.253
          ansible_user:       "{{ vault_asa_user }}"
          ansible_password:   "{{ vault_asa_pass }}"
          ansible_become:     true
          ansible_become_method: enable
          ansible_become_pass: "{{ vault_asa_enable }}"
          ansible_connection: ansible.netcommon.network_cli
          ansible_network_os: cisco.asa.asa
